#!/bin/bash

echo "🚀 Quick Deploy Script for Streamlit Community Cloud"
echo "============================================="
echo ""
echo "1. First, create a GitHub repository:"
echo "   - Go to https://github.com/new"
echo "   - Name: referral-credit-calculator (or similar)"
echo "   - Make it PUBLIC for free Streamlit hosting"
echo "   - Don't initialize with README (we already have files)"
echo ""
echo "2. Then run these commands in PowerShell:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/YOUR_REPO_NAME.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. Deploy on Streamlit Cloud:"
echo "   - Visit: https://share.streamlit.io"
echo "   - Sign in with GitHub"
echo "   - Click 'New app'"
echo "   - Select your repository"
echo "   - Main file: referral_calculator.py"
echo "   - Click 'Deploy!'"
echo ""
echo "🎉 Your app will be live at: https://YOUR_USERNAME-YOUR_REPO-NAME-main-referral-calc-abc123.streamlit.app"
echo ""
echo "📱 Features ready for public use:"
echo "   ✅ Mobile-friendly interface"
echo "   ✅ User-friendly tooltips and explanations"
echo "   ✅ Export functionality"
echo "   ✅ What-if analysis charts"
echo "   ✅ Professional design"
